.PHONY: clean All

All:
	@echo "----------Building project:[ lines - Debug ]----------"
	@cd "/home/gnutella/code/new houses/lines" && "$(MAKE)" -f  "lines.mk"
clean:
	@echo "----------Cleaning project:[ lines - Debug ]----------"
	@cd "/home/gnutella/code/new houses/lines" && "$(MAKE)" -f  "lines.mk" clean
